### ISSUE TITLE
Fresh install and getting "[ERROR] Error trying (t)o update fan speed"

### ISSUE THREAD

**Issue by SJMarty** [JeffCurless/argoneon#70]
Hello,

I had to reinstall the OS (64-bit Bullseye) on my EON.  I previous had your scripts installed and working for quite some time so I reinstalled and for some reason, the fan isn't kicking on.  I've attached both my argoneon.conf and the argoneon.log (with debugging turned on at the end).

[argoneon.txt](https://github.com/user-attachments/files/17182389/argoneon.txt)
[argoneon.log](https://github.com/user-attachments/files/17182390/argoneon.log)

argon-status -f returns fan speed as 0.

Thanks for any help!

**Comment by JeffCurless** [comment]
Okay, so… the issue is the code is throwing an exception on the following:

bus.write_byte( ADDR_FAN, 100 )

or

bus.write_byte( ADDR_FAN, int(newspeed))

Anything else and we would see a message other than [ERROR] Error trying to update fan speed

we get bus from:

# initialize I2C bus
rev = GPIO.RPI_REVISION
if rev == 2 or rev == 3:
    bus = smbus.SMBus(1)
else:
    bus = smbus.SMBus(0)

So… could you run raspi-config:
select (3) interface options,
select (I5) I2C Enable/Disable automatic loading of I2C Kernel module

and See if that helps? There is/was code to automatically do this however I wonder if that changed…

**Comment by SJMarty** [comment]
Closing as the issue appears to be hardware-related.
